config/routes.rb
GladioApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'
  get "questions/new" # This is only specifically for a new question, we can add more actions later by creating question resources like user
  match '/signup', to: 'users#new',             via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/blog', to: 'static_pages#blog',       via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/help', to: 'static_pages#help',       via: 'get'
  match '/new', to: 'static_pages#new',         via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Makes sure email information enters the database uniformly before saving.
  before_save { self.email = email.downcase }
  # Creates a remember token before saving the user.
  before_create :create_remember_token
  # Adds the password and password_confirmation attributes, requires the presence of the password,
  # requires that they match, adds an authenticate method to compare an encrypted password to the
  # password_digest to authenticate users.
  has_secure_password
  # All users must have a name and it must be less than 50 characters in length.
  validates :name, presence: true, length: { maximum: 50 }
  # Checks whether the submitted email's syntax is a legitimate email syntax.
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  # All users must have a unique and correct email address.
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  # Password must be at least 6 characters long.
  validates :password, length: { minimum: 6 }

  # Returns a random string of length 16.
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  # SHA1 encryption, this is run on every page so it is faster than BCrypt.
  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  	# Privately encrypts a newly generated remember token using the encrypt method above.
    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	# Search the database for a user with this email and password.
  	user = User.find_by(email: params[:session][:email].downcase)
  	# If the user exists and the information is correct, signin.
    if user && user.authenticate(params[:session][:password])
      # Located in the app's helpers folder.
      sign_in user
      # After a successful login, the user is taken to their previously requested page
      # or their personal page.
      redirect_back_or user
    else
      # Flashes the error message on only this page.
      flash.now[:error] = 'Invalid email/password combination'
      # Re-renders the signin page.
      render 'new'
    end
  end

  # Sign out and redirect to home page. The sign_out method is in the sessions_helper.
  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def blog
  end

  def contact
  end

  def help
  end

  def home
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # You must be signed in to even vist the edit page or perform an update request.
  before_action :signed_in_user, only: [:edit, :update]
  # You must be the correct user in order to edit or update anything.
  before_action :correct_user,   only: [:edit, :update]

  # User variable is the one associated with the current id.
  def show
    @user = User.find(params[:id])
  end

  # User variable is the newly created user.
  def new
  	@user = User.new
  end

  def create
    # User variable is equal to the attempted created user with submitted parameters.
    @user = User.new(user_params)
    # If user successfully saves, sign in the user, flash success, and redirect to
    # their personal user page.
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Gladio!"
      redirect_to @user
    else #Else just send them back.
      render 'new'
    end
  end

  def edit
  end

  # If user successfully updates, flash success, sign in the user, and redirect to
  # their personal user page.
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    # Returns the version of the params hash with only the permitted attributes and
    # raises an error if the :user attribute is missing.
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters

    # Stores the attempted location and takes the non signed in user to the sign in page.
    # "store_location" is found in the sessions_helper.
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    # Ensures the user is looking at their personal information when editing or updating,
    # or else they get sent back home. The "current_user?" method is in the sessions_helper.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Gladio"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
  	# Creates a new token.
    remember_token = User.new_remember_token
    # Places the unencrypted token in the browser cookies.
    cookies.permanent[:remember_token] = remember_token
    # Saves the encrypted token to the database.
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    # Sets the current user equal to the given user.
    self.current_user = user
  end

  # Checks if the user is signed in by checking to see if "current_user" exists.
  def signed_in?
    !current_user.nil?
  end

  # Allows "self.current_user" above to work by defining the method.
  def current_user=(user)
    @current_user = user
  end

  # Finds the current user using the remember_token.
  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  # Returns true or false if the requested user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Empties the current_user variable and deletes the cookie.
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  # Redirects to the requested url or to a default url and deletes the info from ":return_to"
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  # Saves the requested url in ":return_to" for friendly forwarding purposes.
  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Gladio
  </small>
  <!-- Begin Footer Links -->
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "Blog", blog_path %></li>
    </ul>
  </nav>
  <!-- End Footer Links -->
</footer>

app/views/layouts/_grid_items.html.erb
<div class="row-fluid">
  <div class="span4">
    <h2>Heading</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn" href="#">View details &raquo;</a></p>
  </div><!--/span-->
  <div class="span4">
    <h2>Heading</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn" href="#">View details &raquo;</a></p>
  </div><!--/span-->
  <div class="span4">
    <h2>Heading</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn" href="#">View details &raquo;</a></p>
  </div><!--/span-->
</div><!--/row-->
<div class="row-fluid">
  <div class="span4">
    <h2>Heading</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn" href="#">View details &raquo;</a></p>
  </div><!--/span-->
  <div class="span4">
    <h2>Heading</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn" href="#">View details &raquo;</a></p>
  </div><!--/span-->
  <div class="span4">
    <h2>Heading</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn" href="#">View details &raquo;</a></p>
  </div><!--/span-->
</div><!--/row-->

app/views/layouts/_header.html.erb
<header>
  The Sword
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="well sidebar-nav">
  <ul class="nav nav-list">
    <li class="nav-header">Guide</li>
    <li><%= link_to "Home", root_path %></li>
    <% if signed_in? %>
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
        <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
    <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
        <li><%= link_to "Sign up", signup_path %></li>
    <% end %>
    <li class="nav-header">Morality</li>
    <li><a href="#">Abortion</a></li>
    <li><a href="#">Death Penalty</a></li>
    <li><a href="#">Euthanasia</a></li>
    <li><a href="#">Homosexuality</a></li>
    <li class="nav-header">History</li>
    <li><a href="#">Early Church Fathers</a></li>
    <li><a href="#">The East-West Schism</a></li>
    <li><a href="#">The Protestant Reformation</a></li>
  </ul>
</div><!--/.well -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <%= full_title(yield(:title)) %>
  </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!-- Take care of older versions of Internet Explorer -->
  <%= render 'layouts/shim' %>
</head>
<body>
  <!-- Begin Sidebar-->
  <%= render 'layouts/sidebar' %>
  <!-- End Sidebar -->
  <!-- Begin Header -->
  <%= render 'layouts/header' %>
  <!-- End Header -->
  <div class="container">
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>
    <div class="row-fluid">
      <div class="span16">
        <div class="hero-unit">
          <!-- Toggles hide/show functionality for the sidebar-->
          <button>Toggle</button>
          <br>
          <%= yield %>
        </div><!--/hero-unit-->
        <!-- Grid items were removed here -->
      </div><!--/span-->
    </div><!--/row-->
  </div><!--/container-->
  <!-- Begin Footer -->
	<div class="container">
    <%= render 'layouts/footer' %>
    <!-- If in development environment, render debug information here -->
    <%= debug(params) if Rails.env.development? %>
  </div>
  <!-- End Footer -->
</body>
</html>

app/views/questions/new.html.erb
<h1>Questions#new</h1>
<p>Find me in app/views/questions/new.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  Gladio seeks to clear the confusion the world has with the Catholic faith through respectful and honest answers about God's plan for our salvation and our relationship with Christ.
</p>

app/views/static_pages/blog.html.erb
<% provide(:title, 'Blog') %>
<h1>Gladio Blog</h1>
<p>Gladio seeks to clear the confusion the world has with the Catholic faith through respectful and honest answers about God's plan for our salvation and our relationship with Christ.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<h1>Contact Us</h1>
<p>
  The Contact page for the Gladio application.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  This page is to provide help!
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<h1>Gladio App</h1>
<p>Gladio seeks to clear the confusion the world has with the Catholic faith through respectful and honest answers about God's plan for our salvation and our relationship with Christ.</p>
<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>

app/views/static_pages/new.html.erb
<% provide(:title, 'New') %>
<h1>Gladio "New" Page</h1>
<p>
  Gladio "New" Page
</p>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<div class ="row span6 offset4">
  <h1>Update your profile</h1>
</div>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div><!--/span6 offset3-->
</div><!--/row-->

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class ="row span6 offset4">
  <h1>Sign up</h1>
</div>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %></h1>